words:
  - avenir
  - clsx
  - grayscale
  - Mingxuan
  - nodenext
  - predeploy
  - prepack
  - reekystive
  - unplugin
  - Vite
  - Vitest
  - WCAG
  - WWDC
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
