onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
patchedDependencies:
  unplugin-dts: patches/unplugin-dts.patch
  eslint-plugin-storybook: patches/eslint-plugin-storybook.patch
